obj-$(CONFIG_ELAN_FINGERPRINT_SPI) += efsa120s.o asus_fp_id.o asus_fp_panel_event.o

obj-$(CONFIG_SYNA_FINGERPRINT_SPI) += vfsspi_drv.o asus_fp_id.o asus_fp_panel_event.o
# obj-$(findstring y, $CONFIG_ELAN_FINGERPRINT_SPI $CONFIG_SYNA_FINGERPRINT_SPI) += asus_fp_id.o
